# This is a basic workflow to help you get started with Actions

name: Export APK

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew  
      - name: Build Android App
        # You may pin to the exact commit or the version.
        # uses: sparkfabrik/android-build-action@02e36921259edb617c8395c1432b3164b3257e8e
        uses: sparkfabrik/android-build-action@v1.0.0
        with:
          # Project path
          project-path:  ./
          # Output path of apk
          output-path: /output.apk
          # Name of the gradle task to exec
          gradle-task: assembleDebug
          # Boolean to tell the Action to upload the .ipa to Browserstack App Live after the build.
          browserstack-upload: false
