name: AndroidLint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  android_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Lint
        run: ./gradlew lint
      - name: Upload Result
        uses: actions/upload-artifact@v2
        with:
         name: LintReport
         path: ${{ github.workspace }}/app/build/reports/lint-results.html
      
